# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

# set a custom mnemonic for the development network
networks:
  default: development
  development:
    cmd_settings:
      mnemonic: hill law jazz limb penalty escape public dish stand bracket blue jar
      default_balance: 5000
  mainnet-fork:
    cmd_settings:
      default_balance: 5000

# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath

compiler:
  solc:
    version: 0.8.6
    optimizer:
      enabled: true
      runs: 200
  vyper:
    version: 0.2.12

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - Uniswap/uniswap-v2-core@1.0.1

# enable output of development artifacts to load with react
dev_deployment_artifacts: true
